services:
  redis:
    image: redis:latest
    container_name: tuya-localkey-extractor-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  cli:
    build: .
    container_name: py-tuya-localkey-extractor-cli
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: python api.py --print

  cli-cache:
    build: .
    container_name: py-tuya-localkey-extractor-cli-cache
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: python api.py --cache --print
  api:
    build: .
    container_name: py-tuya-localkey-extractor-api
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5005:80"
    command: python server.py

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: py-tuya-localkey-extractor-frontend
    depends_on:
      - redis
    ports:
      - "5000:80"