services:
  # Servizio per costruire l'immagine
  tuya-localkey-extractor-backend-image:
    build:
      context: backend
      dockerfile: Dockerfile
    image: tuya-localkey-extractor-backend:latest

  tuya-localkey-extractor-frontend-image:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: tuya-localkey-extractor-frontend:latest

  redis:
    image: redis:latest
    container_name: tuya-localkey-extractor-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  cli:
    image: tuya-localkey-extractor-backend:latest
    container_name: py-tuya-localkey-extractor-cli
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    configs:
      - source: config_json
        target: /app/config.json
    command: python api.py --print

  cli-cache:
    image: tuya-localkey-extractor-backend:latest
    container_name: py-tuya-localkey-extractor-cli-cache
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    configs:
      - source: config_json
        target: /app/config.json
    command: python api.py --cache --print

  api:
    image: tuya-localkey-extractor-backend:latest
    container_name: py-tuya-localkey-extractor-api
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5005:80"
    configs:
      - source: config_json
        target: /app/config.json
    command: python server.py

  frontend:
    image: tuya-localkey-extractor-frontend:latest
    container_name: py-tuya-localkey-extractor-frontend
    depends_on:
      - redis
      - api
    ports:
      - "5000:80"

configs:
  config_json:
    file: ./backend/config.json