services:
  redis:
    image: redis:latest
    container_name: tuya-localkey-extractor-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  app:
    build: .
    container_name: py-tuya-localkey-extractor-app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: python app.py

  dump_redis:
    build: .
    container_name: py-tuya-localkey-extractor-dump-redis
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: python dump_redis.py